# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
    ]
