# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
