# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='owner',
            new_name='manager',
        ),
    ]
