# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20160624_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_name',
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Team', max_length=30),
        ),
    ]
