# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_teams'),
        ('leagues', '0003_auto_20160624_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='teams', to='players.Player'),
        ),
    ]
